// Source of truth: TNeGA DBT Page Migration prompt — the 55-item source
// list had "GOI MBC Post Matric and Pre Matric" twice; already
// deduplicated to 54 unique schemes per that prompt's own note. If the
// duplicate was actually meant to be a distinct "GOI DNC Post Matric and
// Pre Matric" entry, the content team should confirm and this file gets
// the extra line added back.
export const DBT_SCHEMES: string[] = [
  "KALAINGAR MAHALIR URIMAI THITTAM",
  "Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (MRAHEAS) - PPS",
  "ADW - State Scheme Girls Incentives Girls Transgenders (SC) (III to V)",
  "ADW - State Scheme Girls Incentives Girls Transgenders (SC) (VI to VIII)",
  "Prematric Scholarship for BC (TOPUP)",
  "Prematric Scholarship for MBC & DNC (TOPUP)",
  "Monthly Cash Assistance for Government School Boys Perceiving Higher Education (Tamizh Pudhalvan Scheme) - TPS",
  "Maintenance Grant for Differently Abled",
  "Muslim Girls Education Scholarship - WAKF Board",
  "ADW - State Special Post Matric Scholarship",
  "ADW - Tuition Fee Concession",
  "Incentive Scheme for Rural Minority Girls Students of Std 3 to 6",
  "Postmatric Scholarship for MBC & DNC (TOPUP)",
  "Post Matric Scholarship for BC Students (TOPUP)",
  "TW - Girls Incentive Scheme",
  "TW - Higher Education Special Scholarship Scheme",
  "TW - Free Education Concession Post Graduate (Girls)",
  "TW - Free Education Concession Under Graduate Students",
  "TW - Tuition Fee Concession to Law University Students",
  "TW - Tuition Fee Concession to University Students",
  "TW - Tamil Nadu Fellowship for Tribal Research",
  "ADW - Skill Voucher Incentive Scheme",
  "Anbu Karangal Scheme",
  "Rural Girls Incentive Scheme for Most Backward Classes and Denotified Communities Girls Students of Std. III to Std. VI",
  "ADW - Higher Education Special Scholarship",
  "ADW - Free Education UG",
  "ADW - Free Education PG",
  "TNCWWB - Accidental Death and Funeral Assistance - Accidental Death at Work Place and Funeral Assistance",
  "TNCWWB - Accidental Death and Funeral Assistance - Death at Other Than Work Place and Funeral Assistance",
  "TNCWWB - Accidental Death and Funeral Assistance - Handicapped (Disability of Hand, Leg, Eyes)",
  "TNCWWB - Natural Death and Funeral Assistance",
  "TNCWWB - Old Age Pension (Above 60 Years)",
  "TNCWWB - Spectacles Assistance",
  "TNCWWB - Education Assistance - Professional PG Degree Day Scholar",
  "TNCWWB - Education Assistance - Professional UG Degree Day Scholar",
  "TNCWWB - Education Assistance - Arts and Science PG Degree Day Scholar",
  "TNCWWB - Education Assistance - Arts and Science UG Degree Day Scholar",
  "TNCWWB - Education Assistance - ITI or Polytechnic Day Scholar",
  "TNCWWB - Education Assistance - 12th Std Passed (All Genders)",
  "TNCWWB - Education Assistance - Pursuing 12th Std (Only Girls)",
  "TNCWWB - Education Assistance - Pursuing 11th Std (Only Girls)",
  "TNCWWB - Education Assistance - 10th Std Passed (All Genders)",
  "TNCWWB - Education Assistance - Professional UG Degree Hosteller",
  "TNCWWB - Education Assistance - Professional PG Degree Hosteller",
  "TNCWWB - Education Assistance - Arts and Science UG Degree Hosteller",
  "TNCWWB - Education Assistance - Arts and Science PG Degree Hosteller",
  "TNCWWB - Education Assistance - Pursuing 10th Std (Only Girls)",
  "TNCWWB - Education Assistance - ITI or Polytechnic Hosteller",
  "TNCWWB - Maternity Assistance",
  "TNCWWB - Maternity Assistance - Miscarriage / Abortion",
  "TNCWWB - Marriage Assistance (Daughter)",
  "TNCWWB - Marriage Assistance (Son)",
  "TNCWWB - New Higher Education Scholarship Scheme",
  "ADW - Ph.D. Incentive Scheme",
  "GOI SC Post Matric and Pre Matric",
  "GOI BC Post Matric and Pre Matric",
  "GOI MBC Post Matric and Pre Matric",
  "GOI ST Post Matric and Pre Matric",
];
