// Content for Government Orders.
//
// Rows are generated directly from the real PDFs the client uploaded to
// public/documents/government-orders/ (parsed from each filename, not
// hand-typed). Each row's title/ref is the G.O./Letter reference parsed
// straight from its filename (e.g. "2013_GO.(Ms)_No.8.pdf" -> "G.O. (Ms)
// No. 8") -- real filenames only carry a year and reference number, not a
// subject line, so no description/subject is invented here.
// "(Additional Copy)"/"Annexure" suffixes mark filenames that included a
// "(1)" or "_annexure" marker.
//
// One file from the client's upload, 2021_Data_Center_Policy_2021.pdf, is
// not listed here -- it's a policy document, not a government order, and
// was moved to policies-guidelines/ (byte-identical to the copy already
// there, per explicit instruction) rather than left duplicated here.

import type { DocumentFacet, DocumentRow } from "@/components/documents/types";

export const hero = {
  eyebrow: "Official Orders",
  heading: "Government Orders",
  body: "Official Government Orders issued by the IT & Digital Services Department and Tamil Nadu e-Governance Agency.",
  orbs: [
    { color: "mint", className: "-left-16 -top-24 h-[420px] w-[420px]" },
    { color: "peach", className: "-bottom-10 left-[300px] h-[340px] w-[340px]" },
  ] as const,
};

export const tableHeaders = ["Title", "GO No", "Date", "Department", "Download"];

export const facets: DocumentFacet[] = [
  {
    id: "year",
    kind: "select",
    ariaLabel: "Filter by year",
    initial: "all",
    options: [
      { value: "all", label: "All Years" },
      { value: "2025", label: "2025" },
      { value: "2024", label: "2024" },
      { value: "2023", label: "2023" },
      { value: "2022", label: "2022" },
      { value: "2021", label: "2021" },
      { value: "2020", label: "2020" },
      { value: "2019", label: "2019" },
      { value: "2018", label: "2018" },
      { value: "2017", label: "2017" },
      { value: "2016", label: "2016" },
      { value: "2015", label: "2015" },
      { value: "2014", label: "2014" },
      { value: "2013", label: "2013" },
      { value: "2012", label: "2012" },
      { value: "2011", label: "2011" },
      { value: "2010", label: "2010" },
      { value: "2007", label: "2007" },
      { value: "2006", label: "2006" },
      { value: "2002", label: "2002" },
    ],
  },
  {
    id: "dept",
    kind: "select",
    ariaLabel: "Filter by department",
    initial: "all",
    options: [
      { value: "all", label: "All Departments" },
      { value: "itds", label: "IT&DS Department" },
    ],
  },
];

export const rows: DocumentRow[] = [
  {
    id: "go-001",
    searchText: "G.O. (Ms).No. 2",
    facets: { year: "2002" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 2" },
      { kind: "ref", text: "G.O. (Ms).No. 2" },
      { kind: "date", text: "2002" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2002_G.O.(Ms).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 2 PDF" },
    ],
  },
  {
    id: "go-002",
    searchText: "Letter No. 237",
    facets: { year: "2002" },
    cells: [
      { kind: "title", text: "Letter No. 237" },
      { kind: "ref", text: "Letter No. 237" },
      { kind: "date", text: "2002" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2002_Letter_No.237.pdf", label: "PDF", ariaLabel: "Download Letter No. 237 PDF" },
    ],
  },
  {
    id: "go-003",
    searchText: "G.O. Ms No. 4 (Additional Copy)",
    facets: { year: "2006" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 4 (Additional Copy)" },
      { kind: "ref", text: "G.O. Ms No. 4 (Additional Copy)" },
      { kind: "date", text: "2006" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2006_GO.Ms_No.4%20(1).pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 4 (Additional Copy) PDF" },
    ],
  },
  {
    id: "go-004",
    searchText: "G.O. Ms No. 4",
    facets: { year: "2006" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 4" },
      { kind: "ref", text: "G.O. Ms No. 4" },
      { kind: "date", text: "2006" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2006_GO.Ms_No.4.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 4 PDF" },
    ],
  },
  {
    id: "go-005",
    searchText: "G.O. (Ms) No. 17",
    facets: { year: "2007" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 17" },
      { kind: "ref", text: "G.O. (Ms) No. 17" },
      { kind: "date", text: "2007" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2007_G.O._(Ms)_No.17.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 17 PDF" },
    ],
  },
  {
    id: "go-006",
    searchText: "G.O. (Ms) No. 31",
    facets: { year: "2010" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 31" },
      { kind: "ref", text: "G.O. (Ms) No. 31" },
      { kind: "date", text: "2010" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2010_GO.(Ms)_No.31.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 31 PDF" },
    ],
  },
  {
    id: "go-007",
    searchText: "G.O. (Ms).No. 16",
    facets: { year: "2011" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 16" },
      { kind: "ref", text: "G.O. (Ms).No. 16" },
      { kind: "date", text: "2011" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2011_G.O.(Ms).No.16.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 16 PDF" },
    ],
  },
  {
    id: "go-008",
    searchText: "G.O. 2(D) No. 22",
    facets: { year: "2011" },
    cells: [
      { kind: "title", text: "G.O. 2(D) No. 22" },
      { kind: "ref", text: "G.O. 2(D) No. 22" },
      { kind: "date", text: "2011" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2011_GO.2(D)_No_22.pdf", label: "PDF", ariaLabel: "Download G.O. 2(D) No. 22 PDF" },
    ],
  },
  {
    id: "go-009",
    searchText: "G.O. (Ms) No. 3",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 3" },
      { kind: "ref", text: "G.O. (Ms) No. 3" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO.(Ms)_No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 3 PDF" },
    ],
  },
  {
    id: "go-010",
    searchText: "G.O. (Ms) No. 4",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 4" },
      { kind: "ref", text: "G.O. (Ms) No. 4" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO.(Ms)_No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 4 PDF" },
    ],
  },
  {
    id: "go-011",
    searchText: "G.O. (Ms) No. 5",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 5" },
      { kind: "ref", text: "G.O. (Ms) No. 5" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO.(Ms)_No.5.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 5 PDF" },
    ],
  },
  {
    id: "go-012",
    searchText: "G.O. (2D) No. 2",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. (2D) No. 2" },
      { kind: "ref", text: "G.O. (2D) No. 2" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO._(2D)_No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (2D) No. 2 PDF" },
    ],
  },
  {
    id: "go-013",
    searchText: "G.O. (2D) No. 8",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. (2D) No. 8" },
      { kind: "ref", text: "G.O. (2D) No. 8" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO._(2D)_No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (2D) No. 8 PDF" },
    ],
  },
  {
    id: "go-014",
    searchText: "G.O. (Ms) No. 6",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 6" },
      { kind: "ref", text: "G.O. (Ms) No. 6" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO._(Ms)_No.6.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 6 PDF" },
    ],
  },
  {
    id: "go-015",
    searchText: "G.O. 2(D) No. 4",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. 2(D) No. 4" },
      { kind: "ref", text: "G.O. 2(D) No. 4" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO._2(D)_No.4.pdf", label: "PDF", ariaLabel: "Download G.O. 2(D) No. 4 PDF" },
    ],
  },
  {
    id: "go-016",
    searchText: "G.O. Ms. No. 15",
    facets: { year: "2012" },
    cells: [
      { kind: "title", text: "G.O. Ms. No. 15" },
      { kind: "ref", text: "G.O. Ms. No. 15" },
      { kind: "date", text: "2012" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2012_GO._Ms._No.15.pdf", label: "PDF", ariaLabel: "Download G.O. Ms. No. 15 PDF" },
    ],
  },
  {
    id: "go-017",
    searchText: "G.O. (Ms) No. 22",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 22" },
      { kind: "ref", text: "G.O. (Ms) No. 22" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO.(Ms)_No.22.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 22 PDF" },
    ],
  },
  {
    id: "go-018",
    searchText: "G.O. (Ms) No. 23",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 23" },
      { kind: "ref", text: "G.O. (Ms) No. 23" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO.(Ms)_No.23.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 23 PDF" },
    ],
  },
  {
    id: "go-019",
    searchText: "G.O. (Ms) No. 8",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 8" },
      { kind: "ref", text: "G.O. (Ms) No. 8" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO.(Ms)_No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 8 PDF" },
    ],
  },
  {
    id: "go-020",
    searchText: "G.O. Ms No. 21",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 21" },
      { kind: "ref", text: "G.O. Ms No. 21" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO.Ms_No.21.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 21 PDF" },
    ],
  },
  {
    id: "go-021",
    searchText: "G.O. (MS) No. 14",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (MS) No. 14" },
      { kind: "ref", text: "G.O. (MS) No. 14" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO._(MS)_No.14.pdf", label: "PDF", ariaLabel: "Download G.O. (MS) No. 14 PDF" },
    ],
  },
  {
    id: "go-022",
    searchText: "G.O. (Ms) No. 19",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 19" },
      { kind: "ref", text: "G.O. (Ms) No. 19" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO._(Ms)_No.19.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 19 PDF" },
    ],
  },
  {
    id: "go-023",
    searchText: "G.O. (Ms) No. 3 (Additional Copy)",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 3 (Additional Copy)" },
      { kind: "ref", text: "G.O. (Ms) No. 3 (Additional Copy)" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO._(Ms)_No.3%20(1).pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 3 (Additional Copy) PDF" },
    ],
  },
  {
    id: "go-024",
    searchText: "G.O. (Ms) No. 3",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 3" },
      { kind: "ref", text: "G.O. (Ms) No. 3" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO._(Ms)_No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 3 PDF" },
    ],
  },
  {
    id: "go-025",
    searchText: "G.O. 2(D) No. 42",
    facets: { year: "2013" },
    cells: [
      { kind: "title", text: "G.O. 2(D) No. 42" },
      { kind: "ref", text: "G.O. 2(D) No. 42" },
      { kind: "date", text: "2013" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2013_GO._2(D)_No.42.pdf", label: "PDF", ariaLabel: "Download G.O. 2(D) No. 42 PDF" },
    ],
  },
  {
    id: "go-026",
    searchText: "G.O. (D).No. 36",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 36" },
      { kind: "ref", text: "G.O. (D).No. 36" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_G.O.(D).No.36.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 36 PDF" },
    ],
  },
  {
    id: "go-027",
    searchText: "G.O. (Ms)No. 2",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. (Ms)No. 2" },
      { kind: "ref", text: "G.O. (Ms)No. 2" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_G.O.(Ms)No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms)No. 2 PDF" },
    ],
  },
  {
    id: "go-028",
    searchText: "G.O. (D)No. 28",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. (D)No. 28" },
      { kind: "ref", text: "G.O. (D)No. 28" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.(D)No.28.pdf", label: "PDF", ariaLabel: "Download G.O. (D)No. 28 PDF" },
    ],
  },
  {
    id: "go-029",
    searchText: "G.O. (Ms)No. 4",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. (Ms)No. 4" },
      { kind: "ref", text: "G.O. (Ms)No. 4" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.(Ms)No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms)No. 4 PDF" },
    ],
  },
  {
    id: "go-030",
    searchText: "G.O. (Ms) No. 3",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 3" },
      { kind: "ref", text: "G.O. (Ms) No. 3" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.(Ms)_No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 3 PDF" },
    ],
  },
  {
    id: "go-031",
    searchText: "G.O. 2(D)No. 14",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. 2(D)No. 14" },
      { kind: "ref", text: "G.O. 2(D)No. 14" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.2(D)No.14.pdf", label: "PDF", ariaLabel: "Download G.O. 2(D)No. 14 PDF" },
    ],
  },
  {
    id: "go-032",
    searchText: "G.O. 2(D)No. 17",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. 2(D)No. 17" },
      { kind: "ref", text: "G.O. 2(D)No. 17" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.2(D)No.17.pdf", label: "PDF", ariaLabel: "Download G.O. 2(D)No. 17 PDF" },
    ],
  },
  {
    id: "go-033",
    searchText: "G.O. Ms No. 13",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 13" },
      { kind: "ref", text: "G.O. Ms No. 13" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.Ms_No.13.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 13 PDF" },
    ],
  },
  {
    id: "go-034",
    searchText: "G.O. Ms No. 17",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 17" },
      { kind: "ref", text: "G.O. Ms No. 17" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.Ms_No.17.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 17 PDF" },
    ],
  },
  {
    id: "go-035",
    searchText: "G.O. Ms No. 5",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 5" },
      { kind: "ref", text: "G.O. Ms No. 5" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.Ms_No.5.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 5 PDF" },
    ],
  },
  {
    id: "go-036",
    searchText: "G.O. Ms No. 66",
    facets: { year: "2014" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 66" },
      { kind: "ref", text: "G.O. Ms No. 66" },
      { kind: "date", text: "2014" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2014_GO.Ms_No.66.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 66 PDF" },
    ],
  },
  {
    id: "go-037",
    searchText: "G.O. (D)No. 1",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. (D)No. 1" },
      { kind: "ref", text: "G.O. (D)No. 1" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.(D)No.1.pdf", label: "PDF", ariaLabel: "Download G.O. (D)No. 1 PDF" },
    ],
  },
  {
    id: "go-038",
    searchText: "G.O. (D)No. 4",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. (D)No. 4" },
      { kind: "ref", text: "G.O. (D)No. 4" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.(D)No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (D)No. 4 PDF" },
    ],
  },
  {
    id: "go-039",
    searchText: "G.O. (D)No. 5",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. (D)No. 5" },
      { kind: "ref", text: "G.O. (D)No. 5" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.(D)No.5.pdf", label: "PDF", ariaLabel: "Download G.O. (D)No. 5 PDF" },
    ],
  },
  {
    id: "go-040",
    searchText: "G.O. (Ms).No. 10",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 10" },
      { kind: "ref", text: "G.O. (Ms).No. 10" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.(Ms).No.10.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 10 PDF" },
    ],
  },
  {
    id: "go-041",
    searchText: "G.O. (Ms).No. 12",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 12" },
      { kind: "ref", text: "G.O. (Ms).No. 12" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.(Ms).No.12.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 12 PDF" },
    ],
  },
  {
    id: "go-042",
    searchText: "G.O. (Ms).No. 2",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 2" },
      { kind: "ref", text: "G.O. (Ms).No. 2" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.(Ms).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 2 PDF" },
    ],
  },
  {
    id: "go-043",
    searchText: "G.O. Ms No. 1",
    facets: { year: "2015" },
    cells: [
      { kind: "title", text: "G.O. Ms No. 1" },
      { kind: "ref", text: "G.O. Ms No. 1" },
      { kind: "date", text: "2015" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2015_G.O.Ms_No.1.pdf", label: "PDF", ariaLabel: "Download G.O. Ms No. 1 PDF" },
    ],
  },
  {
    id: "go-044",
    searchText: "G.O. (D).No. 13",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 13" },
      { kind: "ref", text: "G.O. (D).No. 13" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(D).No.13.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 13 PDF" },
    ],
  },
  {
    id: "go-045",
    searchText: "G.O. (D).No. 2",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 2" },
      { kind: "ref", text: "G.O. (D).No. 2" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(D).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 2 PDF" },
    ],
  },
  {
    id: "go-046",
    searchText: "G.O. (D) No. 25",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 25" },
      { kind: "ref", text: "G.O. (D) No. 25" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(D)_No.25.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 25 PDF" },
    ],
  },
  {
    id: "go-047",
    searchText: "G.O. (D) No. 26",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 26" },
      { kind: "ref", text: "G.O. (D) No. 26" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(D)_No.26.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 26 PDF" },
    ],
  },
  {
    id: "go-048",
    searchText: "G.O. (D) No. 3",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 3" },
      { kind: "ref", text: "G.O. (D) No. 3" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(D)_No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 3 PDF" },
    ],
  },
  {
    id: "go-049",
    searchText: "G.O. (Ms).No. 13",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 13" },
      { kind: "ref", text: "G.O. (Ms).No. 13" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(Ms).No.13.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 13 PDF" },
    ],
  },
  {
    id: "go-050",
    searchText: "G.O. (Ms).No. 2",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 2" },
      { kind: "ref", text: "G.O. (Ms).No. 2" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(Ms).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 2 PDF" },
    ],
  },
  {
    id: "go-051",
    searchText: "G.O. (Ms).No. 3",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 3" },
      { kind: "ref", text: "G.O. (Ms).No. 3" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(Ms).No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 3 PDF" },
    ],
  },
  {
    id: "go-052",
    searchText: "G.O. (Ms) No. 4",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 4" },
      { kind: "ref", text: "G.O. (Ms) No. 4" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(Ms)_No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 4 PDF" },
    ],
  },
  {
    id: "go-053",
    searchText: "G.O. (Ms) No. 8",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 8" },
      { kind: "ref", text: "G.O. (Ms) No. 8" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O.(Ms)_No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 8 PDF" },
    ],
  },
  {
    id: "go-054",
    searchText: "G.O. (Ms) No. 10",
    facets: { year: "2016" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 10" },
      { kind: "ref", text: "G.O. (Ms) No. 10" },
      { kind: "date", text: "2016" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2016_G.O_(Ms)_No.10.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 10 PDF" },
    ],
  },
  {
    id: "go-055",
    searchText: "G.O. (2D).No. 4",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 4" },
      { kind: "ref", text: "G.O. (2D).No. 4" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(2D).No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 4 PDF" },
    ],
  },
  {
    id: "go-056",
    searchText: "G.O. (2D).No. 8",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 8" },
      { kind: "ref", text: "G.O. (2D).No. 8" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(2D).No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 8 PDF" },
    ],
  },
  {
    id: "go-057",
    searchText: "G.O. (D).No. 1",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 1" },
      { kind: "ref", text: "G.O. (D).No. 1" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.1.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 1 PDF" },
    ],
  },
  {
    id: "go-058",
    searchText: "G.O. (D).No. 12",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 12" },
      { kind: "ref", text: "G.O. (D).No. 12" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.12.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 12 PDF" },
    ],
  },
  {
    id: "go-059",
    searchText: "G.O. (D).No. 14",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 14" },
      { kind: "ref", text: "G.O. (D).No. 14" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.14.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 14 PDF" },
    ],
  },
  {
    id: "go-060",
    searchText: "G.O. (D).No. 20",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 20" },
      { kind: "ref", text: "G.O. (D).No. 20" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.20.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 20 PDF" },
    ],
  },
  {
    id: "go-061",
    searchText: "G.O. (D).No. 22",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 22" },
      { kind: "ref", text: "G.O. (D).No. 22" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.22.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 22 PDF" },
    ],
  },
  {
    id: "go-062",
    searchText: "G.O. (D).No. 25",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 25" },
      { kind: "ref", text: "G.O. (D).No. 25" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.25.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 25 PDF" },
    ],
  },
  {
    id: "go-063",
    searchText: "G.O. (D).No. 26",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 26" },
      { kind: "ref", text: "G.O. (D).No. 26" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.26.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 26 PDF" },
    ],
  },
  {
    id: "go-064",
    searchText: "G.O. (D).No. 30",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 30" },
      { kind: "ref", text: "G.O. (D).No. 30" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.30.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 30 PDF" },
    ],
  },
  {
    id: "go-065",
    searchText: "G.O. (D).No. 9",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 9" },
      { kind: "ref", text: "G.O. (D).No. 9" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(D).No.9.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 9 PDF" },
    ],
  },
  {
    id: "go-066",
    searchText: "G.O. (Ms).No. 10",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 10" },
      { kind: "ref", text: "G.O. (Ms).No. 10" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.10.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 10 PDF" },
    ],
  },
  {
    id: "go-067",
    searchText: "G.O. (Ms).No. 16",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 16" },
      { kind: "ref", text: "G.O. (Ms).No. 16" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.16.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 16 PDF" },
    ],
  },
  {
    id: "go-068",
    searchText: "G.O. (Ms).No. 18",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 18" },
      { kind: "ref", text: "G.O. (Ms).No. 18" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.18.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 18 PDF" },
    ],
  },
  {
    id: "go-069",
    searchText: "G.O. (Ms).No. 2",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 2" },
      { kind: "ref", text: "G.O. (Ms).No. 2" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 2 PDF" },
    ],
  },
  {
    id: "go-070",
    searchText: "G.O. (Ms).No. 20",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 20" },
      { kind: "ref", text: "G.O. (Ms).No. 20" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.20.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 20 PDF" },
    ],
  },
  {
    id: "go-071",
    searchText: "G.O. (Ms).No. 21",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 21" },
      { kind: "ref", text: "G.O. (Ms).No. 21" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.21.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 21 PDF" },
    ],
  },
  {
    id: "go-072",
    searchText: "G.O. (Ms).No. 22",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 22" },
      { kind: "ref", text: "G.O. (Ms).No. 22" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.22.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 22 PDF" },
    ],
  },
  {
    id: "go-073",
    searchText: "G.O. (Ms).No. 24",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 24" },
      { kind: "ref", text: "G.O. (Ms).No. 24" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.24.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 24 PDF" },
    ],
  },
  {
    id: "go-074",
    searchText: "G.O. (Ms).No. 3",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 3" },
      { kind: "ref", text: "G.O. (Ms).No. 3" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 3 PDF" },
    ],
  },
  {
    id: "go-075",
    searchText: "G.O. (Ms).No. 4",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 4" },
      { kind: "ref", text: "G.O. (Ms).No. 4" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_G.O.(Ms).No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 4 PDF" },
    ],
  },
  {
    id: "go-076",
    searchText: "Letter No. 8212",
    facets: { year: "2017" },
    cells: [
      { kind: "title", text: "Letter No. 8212" },
      { kind: "ref", text: "Letter No. 8212" },
      { kind: "date", text: "2017" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2017_Letter_No.8212.pdf", label: "PDF", ariaLabel: "Download Letter No. 8212 PDF" },
    ],
  },
  {
    id: "go-077",
    searchText: "G.O. (2D).No. 8",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 8" },
      { kind: "ref", text: "G.O. (2D).No. 8" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O%2C(2D).No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 8 PDF" },
    ],
  },
  {
    id: "go-078",
    searchText: "G.O. (2D).No. 9",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 9" },
      { kind: "ref", text: "G.O. (2D).No. 9" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O%2C(2D).No.9.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 9 PDF" },
    ],
  },
  {
    id: "go-079",
    searchText: "G.O. (D).No. 19",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 19" },
      { kind: "ref", text: "G.O. (D).No. 19" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O%2C(D).No.19.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 19 PDF" },
    ],
  },
  {
    id: "go-080",
    searchText: "G.O. (Ms).No. 1",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 1" },
      { kind: "ref", text: "G.O. (Ms).No. 1" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O%2C(Ms).No.1.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 1 PDF" },
    ],
  },
  {
    id: "go-081",
    searchText: "G.O. (Ms).No. 13",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 13" },
      { kind: "ref", text: "G.O. (Ms).No. 13" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O%2C(Ms).No.13.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 13 PDF" },
    ],
  },
  {
    id: "go-082",
    searchText: "G.O. (Ms).No. 3",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 3" },
      { kind: "ref", text: "G.O. (Ms).No. 3" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O%2C(Ms).No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 3 PDF" },
    ],
  },
  {
    id: "go-083",
    searchText: "G.O. (2D).No. 10",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 10" },
      { kind: "ref", text: "G.O. (2D).No. 10" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(2D).No.10.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 10 PDF" },
    ],
  },
  {
    id: "go-084",
    searchText: "G.O. (2D).No. 11",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 11" },
      { kind: "ref", text: "G.O. (2D).No. 11" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(2D).No.11.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 11 PDF" },
    ],
  },
  {
    id: "go-085",
    searchText: "G.O. (2D).No. 6",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 6" },
      { kind: "ref", text: "G.O. (2D).No. 6" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(2D).No.6.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 6 PDF" },
    ],
  },
  {
    id: "go-086",
    searchText: "G.O. (D).No. 24",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 24" },
      { kind: "ref", text: "G.O. (D).No. 24" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(D).No.24.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 24 PDF" },
    ],
  },
  {
    id: "go-087",
    searchText: "G.O. (D).No. 33",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 33" },
      { kind: "ref", text: "G.O. (D).No. 33" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(D).No.33.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 33 PDF" },
    ],
  },
  {
    id: "go-088",
    searchText: "G.O. (D).No. 1",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 1" },
      { kind: "ref", text: "G.O. (D).No. 1" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(D).No._1.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 1 PDF" },
    ],
  },
  {
    id: "go-089",
    searchText: "G.O. (D). No. 33",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (D). No. 33" },
      { kind: "ref", text: "G.O. (D). No. 33" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(D)._No.33.pdf", label: "PDF", ariaLabel: "Download G.O. (D). No. 33 PDF" },
    ],
  },
  {
    id: "go-090",
    searchText: "G.O. (Ms).No. 12",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 12" },
      { kind: "ref", text: "G.O. (Ms).No. 12" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(Ms).No.12.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 12 PDF" },
    ],
  },
  {
    id: "go-091",
    searchText: "G.O. (Ms).No. 17",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 17" },
      { kind: "ref", text: "G.O. (Ms).No. 17" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(Ms).No.17.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 17 PDF" },
    ],
  },
  {
    id: "go-092",
    searchText: "G.O. (Ms).No. 19",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 19" },
      { kind: "ref", text: "G.O. (Ms).No. 19" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(Ms).No.19.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 19 PDF" },
    ],
  },
  {
    id: "go-093",
    searchText: "G.O. (Ms).No. 23 (Additional Copy)",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 23 (Additional Copy)" },
      { kind: "ref", text: "G.O. (Ms).No. 23 (Additional Copy)" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(Ms).No.23%20(1).pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 23 (Additional Copy) PDF" },
    ],
  },
  {
    id: "go-094",
    searchText: "G.O. (Ms).No. 23",
    facets: { year: "2018" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 23" },
      { kind: "ref", text: "G.O. (Ms).No. 23" },
      { kind: "date", text: "2018" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2018_G.O.(Ms).No.23.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 23 PDF" },
    ],
  },
  {
    id: "go-095",
    searchText: "G.O. (2D).No. 4",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 4" },
      { kind: "ref", text: "G.O. (2D).No. 4" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(2D).No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 4 PDF" },
    ],
  },
  {
    id: "go-096",
    searchText: "G.O. (2D).No. 5",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 5" },
      { kind: "ref", text: "G.O. (2D).No. 5" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(2D).No.5.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 5 PDF" },
    ],
  },
  {
    id: "go-097",
    searchText: "G.O. (D).No. 14",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 14" },
      { kind: "ref", text: "G.O. (D).No. 14" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.14.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 14 PDF" },
    ],
  },
  {
    id: "go-098",
    searchText: "G.O. (D).No. 15",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 15" },
      { kind: "ref", text: "G.O. (D).No. 15" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.15.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 15 PDF" },
    ],
  },
  {
    id: "go-099",
    searchText: "G.O. (D).No. 16",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 16" },
      { kind: "ref", text: "G.O. (D).No. 16" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.16.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 16 PDF" },
    ],
  },
  {
    id: "go-100",
    searchText: "G.O. (D).No. 17",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 17" },
      { kind: "ref", text: "G.O. (D).No. 17" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.17.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 17 PDF" },
    ],
  },
  {
    id: "go-101",
    searchText: "G.O. (D).No. 18",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 18" },
      { kind: "ref", text: "G.O. (D).No. 18" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.18.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 18 PDF" },
    ],
  },
  {
    id: "go-102",
    searchText: "G.O. (D).No. 19",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 19" },
      { kind: "ref", text: "G.O. (D).No. 19" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.19.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 19 PDF" },
    ],
  },
  {
    id: "go-103",
    searchText: "G.O. (D).No. 21",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 21" },
      { kind: "ref", text: "G.O. (D).No. 21" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.21.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 21 PDF" },
    ],
  },
  {
    id: "go-104",
    searchText: "G.O. (D).No. 22",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 22" },
      { kind: "ref", text: "G.O. (D).No. 22" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.22.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 22 PDF" },
    ],
  },
  {
    id: "go-105",
    searchText: "G.O. (D).No. 28",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 28" },
      { kind: "ref", text: "G.O. (D).No. 28" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.28.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 28 PDF" },
    ],
  },
  {
    id: "go-106",
    searchText: "G.O. (D).No. 29",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 29" },
      { kind: "ref", text: "G.O. (D).No. 29" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.29.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 29 PDF" },
    ],
  },
  {
    id: "go-107",
    searchText: "G.O. (D).No. 35",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 35" },
      { kind: "ref", text: "G.O. (D).No. 35" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.35.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 35 PDF" },
    ],
  },
  {
    id: "go-108",
    searchText: "G.O. (D).No. 36",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 36" },
      { kind: "ref", text: "G.O. (D).No. 36" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.36.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 36 PDF" },
    ],
  },
  {
    id: "go-109",
    searchText: "G.O. (D).No. 37",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 37" },
      { kind: "ref", text: "G.O. (D).No. 37" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.37.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 37 PDF" },
    ],
  },
  {
    id: "go-110",
    searchText: "G.O. (D).No. 38",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 38" },
      { kind: "ref", text: "G.O. (D).No. 38" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.38.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 38 PDF" },
    ],
  },
  {
    id: "go-111",
    searchText: "G.O. (D).No. 43",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 43" },
      { kind: "ref", text: "G.O. (D).No. 43" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.43.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 43 PDF" },
    ],
  },
  {
    id: "go-112",
    searchText: "G.O. (D).No. 44",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 44" },
      { kind: "ref", text: "G.O. (D).No. 44" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.44.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 44 PDF" },
    ],
  },
  {
    id: "go-113",
    searchText: "G.O. (D).No. 45",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 45" },
      { kind: "ref", text: "G.O. (D).No. 45" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.45.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 45 PDF" },
    ],
  },
  {
    id: "go-114",
    searchText: "G.O. (D).No. 48",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 48" },
      { kind: "ref", text: "G.O. (D).No. 48" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.48.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 48 PDF" },
    ],
  },
  {
    id: "go-115",
    searchText: "G.O. (D).No. 8",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 8" },
      { kind: "ref", text: "G.O. (D).No. 8" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(D).No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 8 PDF" },
    ],
  },
  {
    id: "go-116",
    searchText: "G.O. (Ms).No. 10 (Additional Copy)",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 10 (Additional Copy)" },
      { kind: "ref", text: "G.O. (Ms).No. 10 (Additional Copy)" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(Ms).No.10%20(1).pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 10 (Additional Copy) PDF" },
    ],
  },
  {
    id: "go-117",
    searchText: "G.O. (Ms).No. 10",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 10" },
      { kind: "ref", text: "G.O. (Ms).No. 10" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(Ms).No.10.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 10 PDF" },
    ],
  },
  {
    id: "go-118",
    searchText: "G.O. (Ms).No. 12",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 12" },
      { kind: "ref", text: "G.O. (Ms).No. 12" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(Ms).No.12.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 12 PDF" },
    ],
  },
  {
    id: "go-119",
    searchText: "G.O. (Ms).No. 2",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 2" },
      { kind: "ref", text: "G.O. (Ms).No. 2" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(Ms).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 2 PDF" },
    ],
  },
  {
    id: "go-120",
    searchText: "G.O. (Ms).No. 9",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 9" },
      { kind: "ref", text: "G.O. (Ms).No. 9" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_G.O.(Ms).No.9.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 9 PDF" },
    ],
  },
  {
    id: "go-121",
    searchText: "G.O. (D).No. 30",
    facets: { year: "2019" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 30" },
      { kind: "ref", text: "G.O. (D).No. 30" },
      { kind: "date", text: "2019" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2019_GO.(D).No.30.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 30 PDF" },
    ],
  },
  {
    id: "go-122",
    searchText: "G.O. (2D).No. 2",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (2D).No. 2" },
      { kind: "ref", text: "G.O. (2D).No. 2" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(2D).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (2D).No. 2 PDF" },
    ],
  },
  {
    id: "go-123",
    searchText: "G.O. (2D.).No. 4",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (2D.).No. 4" },
      { kind: "ref", text: "G.O. (2D.).No. 4" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(2D.).No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (2D.).No. 4 PDF" },
    ],
  },
  {
    id: "go-124",
    searchText: "G.O. (D).No. 14",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 14" },
      { kind: "ref", text: "G.O. (D).No. 14" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(D).No.14.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 14 PDF" },
    ],
  },
  {
    id: "go-125",
    searchText: "G.O. (D).No. 2",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 2" },
      { kind: "ref", text: "G.O. (D).No. 2" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(D).No.2.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 2 PDF" },
    ],
  },
  {
    id: "go-126",
    searchText: "G.O. (D).No. 3",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 3" },
      { kind: "ref", text: "G.O. (D).No. 3" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(D).No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 3 PDF" },
    ],
  },
  {
    id: "go-127",
    searchText: "G.O. (D.).No. 21",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (D.).No. 21" },
      { kind: "ref", text: "G.O. (D.).No. 21" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(D.).No.21.pdf", label: "PDF", ariaLabel: "Download G.O. (D.).No. 21 PDF" },
    ],
  },
  {
    id: "go-128",
    searchText: "G.O. (D.).No. 24",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (D.).No. 24" },
      { kind: "ref", text: "G.O. (D.).No. 24" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(D.).No.24.pdf", label: "PDF", ariaLabel: "Download G.O. (D.).No. 24 PDF" },
    ],
  },
  {
    id: "go-129",
    searchText: "G.O. (D.).No. 26",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (D.).No. 26" },
      { kind: "ref", text: "G.O. (D.).No. 26" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(D.).No.26.pdf", label: "PDF", ariaLabel: "Download G.O. (D.).No. 26 PDF" },
    ],
  },
  {
    id: "go-130",
    searchText: "G.O. (MS.).No. 26",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (MS.).No. 26" },
      { kind: "ref", text: "G.O. (MS.).No. 26" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(MS.).No.26.pdf", label: "PDF", ariaLabel: "Download G.O. (MS.).No. 26 PDF" },
    ],
  },
  {
    id: "go-131",
    searchText: "G.O. (Ms).No. 11",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 11" },
      { kind: "ref", text: "G.O. (Ms).No. 11" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.11.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 11 PDF" },
    ],
  },
  {
    id: "go-132",
    searchText: "G.O. (Ms).No. 12",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 12" },
      { kind: "ref", text: "G.O. (Ms).No. 12" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.12.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 12 PDF" },
    ],
  },
  {
    id: "go-133",
    searchText: "G.O. (Ms).No. 13",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 13" },
      { kind: "ref", text: "G.O. (Ms).No. 13" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.13.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 13 PDF" },
    ],
  },
  {
    id: "go-134",
    searchText: "G.O. (Ms).No. 15",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 15" },
      { kind: "ref", text: "G.O. (Ms).No. 15" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.15.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 15 PDF" },
    ],
  },
  {
    id: "go-135",
    searchText: "G.O. (Ms).No. 24",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 24" },
      { kind: "ref", text: "G.O. (Ms).No. 24" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.24.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 24 PDF" },
    ],
  },
  {
    id: "go-136",
    searchText: "G.O. (Ms).No. 25",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 25" },
      { kind: "ref", text: "G.O. (Ms).No. 25" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.25.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 25 PDF" },
    ],
  },
  {
    id: "go-137",
    searchText: "G.O. (Ms).No. 27",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 27" },
      { kind: "ref", text: "G.O. (Ms).No. 27" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.27.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 27 PDF" },
    ],
  },
  {
    id: "go-138",
    searchText: "G.O. (Ms).No. 28",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 28" },
      { kind: "ref", text: "G.O. (Ms).No. 28" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.28.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 28 PDF" },
    ],
  },
  {
    id: "go-139",
    searchText: "G.O. (Ms).No. 3",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 3" },
      { kind: "ref", text: "G.O. (Ms).No. 3" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 3 PDF" },
    ],
  },
  {
    id: "go-140",
    searchText: "G.O. (Ms).No. 30",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 30" },
      { kind: "ref", text: "G.O. (Ms).No. 30" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.30.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 30 PDF" },
    ],
  },
  {
    id: "go-141",
    searchText: "G.O. (Ms).No. 4",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 4" },
      { kind: "ref", text: "G.O. (Ms).No. 4" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 4 PDF" },
    ],
  },
  {
    id: "go-142",
    searchText: "G.O. (Ms).No. 8",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 8" },
      { kind: "ref", text: "G.O. (Ms).No. 8" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No.8.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 8 PDF" },
    ],
  },
  {
    id: "go-143",
    searchText: "G.O. (Ms).No. 1",
    facets: { year: "2020" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 1" },
      { kind: "ref", text: "G.O. (Ms).No. 1" },
      { kind: "date", text: "2020" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2020_G.O.(Ms).No._1.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 1 PDF" },
    ],
  },
  {
    id: "go-144",
    searchText: "G.O. (2D). No. 1",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (2D). No. 1" },
      { kind: "ref", text: "G.O. (2D). No. 1" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(2D)._No.1.pdf", label: "PDF", ariaLabel: "Download G.O. (2D). No. 1 PDF" },
    ],
  },
  {
    id: "go-145",
    searchText: "G.O. (2D) No. 4",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (2D) No. 4" },
      { kind: "ref", text: "G.O. (2D) No. 4" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(2D)_No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (2D) No. 4 PDF" },
    ],
  },
  {
    id: "go-146",
    searchText: "G.O. (D) No. 23",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 23" },
      { kind: "ref", text: "G.O. (D) No. 23" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(D)_No.23.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 23 PDF" },
    ],
  },
  {
    id: "go-147",
    searchText: "G.O. (D) No. 29",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 29" },
      { kind: "ref", text: "G.O. (D) No. 29" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(D)_No.29.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 29 PDF" },
    ],
  },
  {
    id: "go-148",
    searchText: "G.O. (Ms).No. 37",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 37" },
      { kind: "ref", text: "G.O. (Ms).No. 37" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms).No._37.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 37 PDF" },
    ],
  },
  {
    id: "go-149",
    searchText: "G.O. (Ms.) No. 14",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 14" },
      { kind: "ref", text: "G.O. (Ms.) No. 14" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.14.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 14 PDF" },
    ],
  },
  {
    id: "go-150",
    searchText: "G.O. (Ms.) No. 17",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 17" },
      { kind: "ref", text: "G.O. (Ms.) No. 17" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.17.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 17 PDF" },
    ],
  },
  {
    id: "go-151",
    searchText: "G.O. (Ms.) No. 18",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 18" },
      { kind: "ref", text: "G.O. (Ms.) No. 18" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.18.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 18 PDF" },
    ],
  },
  {
    id: "go-152",
    searchText: "G.O. (Ms.) No. 33",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 33" },
      { kind: "ref", text: "G.O. (Ms.) No. 33" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.33.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 33 PDF" },
    ],
  },
  {
    id: "go-153",
    searchText: "G.O. (Ms.) No. 33 Annexure",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 33 Annexure" },
      { kind: "ref", text: "G.O. (Ms.) No. 33 Annexure" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.33_annexure.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 33 Annexure PDF" },
    ],
  },
  {
    id: "go-154",
    searchText: "G.O. (Ms.) No. 35",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 35" },
      { kind: "ref", text: "G.O. (Ms.) No. 35" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.35.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 35 PDF" },
    ],
  },
  {
    id: "go-155",
    searchText: "G.O. (Ms.) No. 37",
    facets: { year: "2021" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 37" },
      { kind: "ref", text: "G.O. (Ms.) No. 37" },
      { kind: "date", text: "2021" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2021_G.O.(Ms.)_No.37.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 37 PDF" },
    ],
  },
  {
    id: "go-156",
    searchText: "G.O. (D) No. 15",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 15" },
      { kind: "ref", text: "G.O. (D) No. 15" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(D)_No.15.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 15 PDF" },
    ],
  },
  {
    id: "go-157",
    searchText: "G.O. (Ms) No. 16",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 16" },
      { kind: "ref", text: "G.O. (Ms) No. 16" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.16.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 16 PDF" },
    ],
  },
  {
    id: "go-158",
    searchText: "G.O. (Ms) No. 23",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 23" },
      { kind: "ref", text: "G.O. (Ms) No. 23" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.23.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 23 PDF" },
    ],
  },
  {
    id: "go-159",
    searchText: "G.O. (Ms) No. 26",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 26" },
      { kind: "ref", text: "G.O. (Ms) No. 26" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.26.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 26 PDF" },
    ],
  },
  {
    id: "go-160",
    searchText: "G.O. (Ms) No. 3",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 3" },
      { kind: "ref", text: "G.O. (Ms) No. 3" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.3.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 3 PDF" },
    ],
  },
  {
    id: "go-161",
    searchText: "G.O. (Ms) No. 32",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 32" },
      { kind: "ref", text: "G.O. (Ms) No. 32" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.32.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 32 PDF" },
    ],
  },
  {
    id: "go-162",
    searchText: "G.O. (Ms) No. 33",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 33" },
      { kind: "ref", text: "G.O. (Ms) No. 33" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.33.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 33 PDF" },
    ],
  },
  {
    id: "go-163",
    searchText: "G.O. (Ms) No. 37",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 37" },
      { kind: "ref", text: "G.O. (Ms) No. 37" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.37.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 37 PDF" },
    ],
  },
  {
    id: "go-164",
    searchText: "G.O. (Ms) No. 4",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 4" },
      { kind: "ref", text: "G.O. (Ms) No. 4" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_G.O.(Ms)_No.4.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 4 PDF" },
    ],
  },
  {
    id: "go-165",
    searchText: "G.O. (Ms) No. 1",
    facets: { year: "2022" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 1" },
      { kind: "ref", text: "G.O. (Ms) No. 1" },
      { kind: "date", text: "2022" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2022_GO.(Ms)_No.01.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 1 PDF" },
    ],
  },
  {
    id: "go-166",
    searchText: "G.O. (D) No. 22",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 22" },
      { kind: "ref", text: "G.O. (D) No. 22" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(D)_No.22.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 22 PDF" },
    ],
  },
  {
    id: "go-167",
    searchText: "G.O. (D) No. 27",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 27" },
      { kind: "ref", text: "G.O. (D) No. 27" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(D)_No.27.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 27 PDF" },
    ],
  },
  {
    id: "go-168",
    searchText: "G.O. (Ms) No. 9",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 9" },
      { kind: "ref", text: "G.O. (Ms) No. 9" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(Ms)_No.09.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 9 PDF" },
    ],
  },
  {
    id: "go-169",
    searchText: "G.O. (Ms) No. 11",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 11" },
      { kind: "ref", text: "G.O. (Ms) No. 11" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(Ms)_No.11.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 11 PDF" },
    ],
  },
  {
    id: "go-170",
    searchText: "G.O. (Ms) No. 18",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 18" },
      { kind: "ref", text: "G.O. (Ms) No. 18" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(Ms)_No.18.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 18 PDF" },
    ],
  },
  {
    id: "go-171",
    searchText: "G.O. (Ms) No. 26",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 26" },
      { kind: "ref", text: "G.O. (Ms) No. 26" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(Ms)_No.26.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 26 PDF" },
    ],
  },
  {
    id: "go-172",
    searchText: "G.O. (Ms) No. 30",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 30" },
      { kind: "ref", text: "G.O. (Ms) No. 30" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(Ms)_No.30.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 30 PDF" },
    ],
  },
  {
    id: "go-173",
    searchText: "G.O. (Ms) No. 31",
    facets: { year: "2023" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 31" },
      { kind: "ref", text: "G.O. (Ms) No. 31" },
      { kind: "date", text: "2023" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2023_G.O.(Ms)_No.31.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 31 PDF" },
    ],
  },
  {
    id: "go-174",
    searchText: "G.O. (D).No. 2",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 2" },
      { kind: "ref", text: "G.O. (D).No. 2" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(D).No._02.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 2 PDF" },
    ],
  },
  {
    id: "go-175",
    searchText: "G.O. (Ms).No. 5",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 5" },
      { kind: "ref", text: "G.O. (Ms).No. 5" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(Ms).No._05.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 5 PDF" },
    ],
  },
  {
    id: "go-176",
    searchText: "G.O. (Ms).No. 1",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 1" },
      { kind: "ref", text: "G.O. (Ms).No. 1" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(Ms).No._1.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 1 PDF" },
    ],
  },
  {
    id: "go-177",
    searchText: "G.O. (Ms).No. 21",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (Ms).No. 21" },
      { kind: "ref", text: "G.O. (Ms).No. 21" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(Ms).No._21.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms).No. 21 PDF" },
    ],
  },
  {
    id: "go-178",
    searchText: "G.O. (Ms) No. 25",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 25" },
      { kind: "ref", text: "G.O. (Ms) No. 25" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(Ms)_No.25.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 25 PDF" },
    ],
  },
  {
    id: "go-179",
    searchText: "G.O. (Ms) No. 29",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (Ms) No. 29" },
      { kind: "ref", text: "G.O. (Ms) No. 29" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(Ms)_No.29.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms) No. 29 PDF" },
    ],
  },
  {
    id: "go-180",
    searchText: "G.O. (Ms.) No. 22",
    facets: { year: "2024" },
    cells: [
      { kind: "title", text: "G.O. (Ms.) No. 22" },
      { kind: "ref", text: "G.O. (Ms.) No. 22" },
      { kind: "date", text: "2024" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2024_G.O.(Ms.)_No.22.pdf", label: "PDF", ariaLabel: "Download G.O. (Ms.) No. 22 PDF" },
    ],
  },
  {
    id: "go-181",
    searchText: "G.O. (D).No. 14",
    facets: { year: "2025" },
    cells: [
      { kind: "title", text: "G.O. (D).No. 14" },
      { kind: "ref", text: "G.O. (D).No. 14" },
      { kind: "date", text: "2025" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2025_G.O.(D).No._14.pdf", label: "PDF", ariaLabel: "Download G.O. (D).No. 14 PDF" },
    ],
  },
  {
    id: "go-182",
    searchText: "G.O. (D) No. 34",
    facets: { year: "2025" },
    cells: [
      { kind: "title", text: "G.O. (D) No. 34" },
      { kind: "ref", text: "G.O. (D) No. 34" },
      { kind: "date", text: "2025" },
      { kind: "badge", text: "IT&DS Department", tone: "sky" },
      { kind: "download", href: "/documents/government-orders/2025_G.O.(D)_No._34.pdf", label: "PDF", ariaLabel: "Download G.O. (D) No. 34 PDF" },
    ],
  },
];

export const searchPlaceholder = "Search government orders...";
export const noResultsText = "No government orders match your filters.";
