/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    media: Media;
    announcements: Announcement;
    'media-items': MediaItem;
    'job-openings': JobOpening;
    'team-members': TeamMember;
    services: Service;
    documents: Document;
    'government-orders': GovernmentOrder;
    policies: Policy;
    'activity-log': ActivityLog;
    'legal-pages': LegalPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'media-items': MediaItemsSelect<false> | MediaItemsSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'government-orders': GovernmentOrdersSelect<false> | GovernmentOrdersSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'nav-content': NavContent;
    'board-content': BoardContent;
    'hero-content': HeroContent;
    'leadership-band-content': LeadershipBandContent;
    'footer-content': FooterContent;
  };
  globalsSelect: {
    'nav-content': NavContentSelect<false> | NavContentSelect<true>;
    'board-content': BoardContentSelect<false> | BoardContentSelect<true>;
    'hero-content': HeroContentSelect<false> | HeroContentSelect<true>;
    'leadership-band-content': LeadershipBandContentSelect<false> | LeadershipBandContentSelect<true>;
    'footer-content': FooterContentSelect<false> | FooterContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  name?: string | null;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the photo for screen readers — required for accessibility.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  heading: string;
  /**
   * Used in the page URL. Auto-filled from the heading — only change this if you need a specific URL.
   */
  slug: string;
  date: string;
  /**
   * Short summary shown on the announcement card (homepage and listing page).
   */
  description: string;
  image?: (number | null) | Media;
  /**
   * Short label shown above the headline on the detail page, e.g. "Service Launch".
   */
  category?: string | null;
  /**
   * Full announcement body, shown on its own page. Leave blank to show only the summary.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional "at a glance" figures shown on the detail page (e.g. Services live: 10).
   */
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show this announcement in the homepage scrolling ticker.
   */
  tickerFeatured?: boolean | null;
  /**
   * Lower numbers show first in the ticker. Only matters when "Show in ticker" is checked.
   */
  tickerOrder?: number | null;
  /**
   * Optional related links shown on the detail page (e.g. to a service or Government Orders).
   */
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-items".
 */
export interface MediaItem {
  id: number;
  type: 'photo' | 'video';
  /**
   * Shown under the thumbnail on the media grid.
   */
  caption: string;
  /**
   * Accessibility description of the image. Falls back to the caption if left blank.
   */
  altText?: string | null;
  /**
   * Only the month and year are shown on the site.
   */
  date: string;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  role: string;
  /**
   * Employment type shown as a small badge, e.g. "Contract" or "Full-time".
   */
  type: string;
  department: string;
  /**
   * Last date to apply.
   */
  deadline: string;
  /**
   * Link to the job description PDF, e.g. /documents/careers/role-name.pdf after dropping the file in public/documents/careers/. Leave blank to hide the Download JD button.
   */
  jdHref?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  /**
   * Use "Vacant" for a currently-unfilled post rather than inventing a name.
   */
  name: string;
  designation: string;
  /**
   * Department/division, e.g. "GIS" or "Procurement/ DRO". Leave blank for the CEO.
   */
  subject?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lower numbers show first. The CEO is normally 0.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * Used in the page URL. Auto-filled from the name.
   */
  slug: string;
  /**
   * Shown on the card and as the About section's opening paragraph.
   */
  description: string;
  /**
   * A single " · "-joined line, e.g. "273 Services · 25,277 Centres · ...".
   */
  stats: string;
  image: number | Media;
  /**
   * Presence decides the CTA/template: set (even "#" as a placeholder) for a citizen-facing "project" with an Access Portal button; leave blank for a department-facing "service" routed to /reach-us.
   */
  accessPortalHref?: string | null;
  /**
   * Every /services tab this item appears under. The first one picked is its "home" section for the breadcrumb and Related carousel.
   */
  sections: ('citizen-services' | 'e-governance-projects' | 'services')[];
  /**
   * Official submitted content for the detail page. Every field here is optional — service-detail-generator.ts fills in sensible generated copy for anything left blank.
   */
  real?: {
    /**
     * Short hero-only line. Falls back to the description above when blank.
     */
    tagline?: string | null;
    /**
     * One stat per row, e.g. "273 Government services".
     */
    statistics?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    keyFeatures?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional, same order as Key Features — a one-line description per feature. Leave a row blank to use the generic fallback for that feature.
     */
    keyFeatureDescriptions?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Statistics normally also become Key Feature cards — check this when Key Features is already complete on its own.
     */
    hideStatFeatureCards?: boolean | null;
    /**
     * "You can use this if..." bullet points.
     */
    eligibility?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    whatYoullNeed?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    faqs?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Extra FAQs shown behind a "View more" toggle.
     */
    faqsMore?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
    aboutSecondParagraph?: string | null;
    hideAboutSecondParagraph?: boolean | null;
    /**
     * A plain callout line in the About section, instead of a generated pull-quote.
     */
    calloutText?: string | null;
    /**
     * Optional link in the About section that opens a modal listing items, e.g. a schemes list.
     */
    aboutLinkModal?: {
      label?: string | null;
      title?: string | null;
      items?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Real product screenshots. Leave empty to show a generated stock-photo carousel instead.
     */
    productTour?:
      | {
          photo: number | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
    productTourCaption?: string | null;
    /**
     * Overrides the generated "How to access" steps. Leave empty and check "Hide steps" below for an intro/outro-only Get Started section with no numbered steps.
     */
    getStartedSteps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Hide the numbered Get Started steps entirely (e.g. intro/outro prose only, like eOffice) rather than showing generated fallback steps.
     */
    suppressGetStartedSteps?: boolean | null;
    getStartedIntro?: string | null;
    getStartedOutro?: string | null;
    /**
     * Label for the Get Started direct-link button (projects only). Defaults to "Open".
     */
    directLinkLabel?: string | null;
    /**
     * Marks a pre-launch project: CTAs become "Coming Soon" / "Contact TNeGA".
     */
    comingSoon?: boolean | null;
    /**
     * Marks an access-gated project (staff login, not public self-service): CTAs become "Avail Service" → /reach-us.
     */
    gatedAccess?: boolean | null;
    /**
     * Overrides the stats line shown on cards elsewhere on the site (the Hero keeps showing the main stats field above).
     */
    relatedCardStats?: string | null;
    /**
     * Overrides the "Project"/"Service" badge label shown on the page — independent of the Project/Service CTA behaviour, which is still driven by Access Portal Link above.
     */
    typeLabel?: ('Project' | 'Service') | null;
    /**
     * Overrides the sitewide footer contact info for this item's Contact section.
     */
    contact?: {
      email?: string | null;
      phone?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * Shown in the media library list — not on the public site.
   */
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "government-orders".
 */
export interface GovernmentOrder {
  id: number;
  /**
   * e.g. "G.O. (Ms).No. 2"
   */
  title: string;
  year: string;
  /**
   * Shown as a badge, e.g. "IT&DS Department"
   */
  department: string;
  file: number | Document;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  /**
   * e.g. "Cyber Security Policy 2020"
   */
  title: string;
  year: string;
  /**
   * Shown as a badge, e.g. "Cyber Security"
   */
  category: string;
  file: number | Document;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  userEmail: string;
  action: 'created' | 'updated' | 'published' | 'unpublished' | 'deleted';
  /**
   * e.g. "Announcements", "Services"
   */
  section: string;
  /**
   * e.g. "Updated "e-Sevai Portal""
   */
  summary: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  /**
   * Which page this content backs — matches a fixed route, not a URL you can change.
   */
  slug: 'privacy-policy' | 'terms-conditions' | 'terms-of-use' | 'disclaimer' | 'help' | 'feedback';
  title: string;
  eyebrow?: string | null;
  intro?: string | null;
  sections?:
    | {
        heading: string;
        /**
         * Separate paragraphs with a blank line. A paragraph where every line starts with "- " renders as a bullet list.
         */
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'media-items';
        value: number | MediaItem;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'government-orders';
        value: number | GovernmentOrder;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  heading?: T;
  slug?: T;
  date?: T;
  description?: T;
  image?: T;
  category?: T;
  body?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  tickerFeatured?: T;
  tickerOrder?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-items_select".
 */
export interface MediaItemsSelect<T extends boolean = true> {
  type?: T;
  caption?: T;
  altText?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  role?: T;
  type?: T;
  department?: T;
  deadline?: T;
  jdHref?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  subject?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  stats?: T;
  image?: T;
  accessPortalHref?: T;
  sections?: T;
  real?:
    | T
    | {
        tagline?: T;
        statistics?:
          | T
          | {
              value?: T;
              id?: T;
            };
        keyFeatures?:
          | T
          | {
              value?: T;
              id?: T;
            };
        keyFeatureDescriptions?:
          | T
          | {
              value?: T;
              id?: T;
            };
        hideStatFeatureCards?: T;
        eligibility?:
          | T
          | {
              value?: T;
              id?: T;
            };
        whatYoullNeed?:
          | T
          | {
              value?: T;
              id?: T;
            };
        faqs?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
        faqsMore?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
        aboutSecondParagraph?: T;
        hideAboutSecondParagraph?: T;
        calloutText?: T;
        aboutLinkModal?:
          | T
          | {
              label?: T;
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
        productTour?:
          | T
          | {
              photo?: T;
              alt?: T;
              id?: T;
            };
        productTourCaption?: T;
        getStartedSteps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        suppressGetStartedSteps?: T;
        getStartedIntro?: T;
        getStartedOutro?: T;
        directLinkLabel?: T;
        comingSoon?: T;
        gatedAccess?: T;
        relatedCardStats?: T;
        typeLabel?: T;
        contact?:
          | T
          | {
              email?: T;
              phone?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "government-orders_select".
 */
export interface GovernmentOrdersSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  department?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  category?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  userEmail?: T;
  action?: T;
  section?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  eyebrow?: T;
  intro?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The header navigation and top accessibility bar, shown on every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-content".
 */
export interface NavContent {
  id: number;
  /**
   * Top bar link label to tn.gov.in, e.g. "தமிழ்நாடு அரசு | Government of Tamil Nadu".
   */
  govLabel: string;
  about?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  notificationsUpdates?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  notificationsDocuments?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Governing Board shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-content".
 */
export interface BoardContent {
  id: number;
  chairman: {
    role: string;
    name: string;
    title: string;
  };
  memberSecretary: {
    role: string;
    name: string;
    title: string;
  };
  /**
   * Regular Governing Board members, shown in the carousel below the two seats above.
   */
  members?:
    | {
        name: string;
        title: string;
        /**
         * Check if this name is a placeholder rather than the real, confirmed appointee — a reminder for editors to replace it once the real name is available. Doesn't change what's shown on the site.
         */
        isPlaceholder?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The homepage Hero — agency name, headline and tagline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-content".
 */
export interface HeroContent {
  id: number;
  /**
   * The bold masthead line the hero cycles through, e.g. the English and Tamil agency name.
   */
  agencyLabelCycle: {
    text: string;
    id?: string | null;
  }[];
  /**
   * The headline, with {word} marking where the animated cycling word goes — e.g. "Powering Digital {word} in Tamil Nadu".
   */
  headlineTemplate: string;
  /**
   * Words that cycle through the {word} placeholder above, e.g. "Governance", "Services".
   */
  headlineCycleWords: {
    word: string;
    id?: string | null;
  }[];
  tagline: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * "Leading Digital Tamil Nadu" band on the homepage — the CM/Minister signature strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-band-content".
 */
export interface LeadershipBandContent {
  id: number;
  description: string;
  /**
   * Exactly two — shown as a larger (first) and smaller (second) signature.
   */
  leaders: {
    name: string;
    title: string;
    photo: number | Media;
    /**
     * CSS object-position for the photo crop, e.g. "50% 20%" to bias toward the top.
     */
    photoPosition?: string | null;
    /**
     * Not currently shown on the site — reserved for future use.
     */
    quote?: string | null;
    id?: string | null;
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The footer shown at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-content".
 */
export interface FooterContent {
  id: number;
  description: string;
  address: string;
  phone: string;
  email: string;
  /**
   * The icon shown is looked up from the platform name, so it must be one of the options below.
   */
  socialLinks?:
    | {
        label: 'Facebook' | 'X' | 'YouTube' | 'Instagram' | 'LinkedIn';
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Quick Links column.
   */
  quickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Citizen Services column.
   */
  citizenServices?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Help & Support column.
   */
  helpSupport?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-content_select".
 */
export interface NavContentSelect<T extends boolean = true> {
  govLabel?: T;
  about?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  services?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  notificationsUpdates?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  notificationsDocuments?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-content_select".
 */
export interface BoardContentSelect<T extends boolean = true> {
  chairman?:
    | T
    | {
        role?: T;
        name?: T;
        title?: T;
      };
  memberSecretary?:
    | T
    | {
        role?: T;
        name?: T;
        title?: T;
      };
  members?:
    | T
    | {
        name?: T;
        title?: T;
        isPlaceholder?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-content_select".
 */
export interface HeroContentSelect<T extends boolean = true> {
  agencyLabelCycle?:
    | T
    | {
        text?: T;
        id?: T;
      };
  headlineTemplate?: T;
  headlineCycleWords?:
    | T
    | {
        word?: T;
        id?: T;
      };
  tagline?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership-band-content_select".
 */
export interface LeadershipBandContentSelect<T extends boolean = true> {
  description?: T;
  leaders?:
    | T
    | {
        name?: T;
        title?: T;
        photo?: T;
        photoPosition?: T;
        quote?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-content_select".
 */
export interface FooterContentSelect<T extends boolean = true> {
  description?: T;
  address?: T;
  phone?: T;
  email?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  quickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  citizenServices?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  helpSupport?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}